/**
 * Combined Compliance Report Generator
 *
 * Generates a unified report combining AI Act classification,
 * accessibility assessment (AAIA), and FRIA results into a
 * single compliance document.
 */

import type { ClassificationResult } from '@eucompliance/ai-act-classifier'
import type { AAIAResult } from '@eucompliance/accessibility-bridge'
import type { FRIAReport } from '@eucompliance/fria-generator'

export interface ComplianceReportInput {
  systemName: string
  organization: string
  classification: ClassificationResult
  aaia?: AAIAResult
  fria?: FRIAReport
  date?: string
}

export function generateComplianceReport(input: ComplianceReportInput): string {
  const date = input.date ?? new Date().toISOString().split('T')[0]

  let report = `# EU AI Act Compliance Report

## ${input.systemName}

| Field | Value |
|-------|-------|
| Organization | ${input.organization} |
| Risk Level | **${input.classification.riskLevel.toUpperCase()}** |
| Confidence | ${Math.round(input.classification.confidence * 100)}% |
| Accessibility Required | ${input.classification.accessibilityRequired ? 'Yes (Article 16(l))' : 'No'} |
| Date | ${date} |

---

## 1. Risk Classification

**Risk level:** ${input.classification.riskLevel.toUpperCase()}

**Reasoning:** ${input.classification.reasoning}

`

  if (input.classification.applicableAnnexItems.length > 0) {
    report += `**Applicable Annex III categories:**
`
    for (const item of input.classification.applicableAnnexItems) {
      report += `- ${item}\n`
    }
    report += `\n`
  }

  report += `**Obligations:**
`
  for (const obligation of input.classification.obligations) {
    report += `- ${obligation}\n`
  }
  report += `\n`

  // AAIA section
  if (input.aaia) {
    report += `---

## 2. AI Accessibility Impact Assessment (AAIA)

**Compliance required:** ${input.aaia.complianceRequired ? 'Yes' : 'No'}

| Priority | Count |
|----------|-------|
| Critical | ${input.aaia.summary.critical} |
| High | ${input.aaia.summary.high} |
| Medium | ${input.aaia.summary.medium} |
| Low | ${input.aaia.summary.low} |
| **Total** | **${input.aaia.summary.totalRequirements}** |

### Requirements

`
    for (const req of input.aaia.requirements) {
      report += `#### [${req.priority.toUpperCase()}] ${req.clauseTitle} (EN 301 549 ${req.clauseId})

**Source:** ${req.sourceArticle}
**Rationale:** ${req.rationale}

**Guidance:**
`
      for (const g of req.guidance) {
        report += `- ${g}\n`
      }
      report += `\n`
    }
  }

  // FRIA section
  if (input.fria) {
    report += `---

## 3. Fundamental Rights Impact Assessment (FRIA)

**Article 27 applicable:** ${input.fria.metadata.article27Applicable ? 'Yes' : 'No'}
**Affected population:** ${input.fria.affectedPopulation}

| Metric | Value |
|--------|-------|
| Rights assessed | ${input.fria.summary.totalRightsAssessed} |
| High relevance | ${input.fria.summary.highRelevance} |
| Medium relevance | ${input.fria.summary.mediumRelevance} |
| Disability risks | ${input.fria.summary.disabilityRisksIdentified} |

### Mitigation Priorities

`
    for (let i = 0; i < input.fria.mitigationPriorities.length; i++) {
      report += `${i + 1}. ${input.fria.mitigationPriorities[i]}\n`
    }
    report += `\n`
  }

  report += `---

## Next Steps

`

  if (input.classification.riskLevel === 'high') {
    report += `1. Address all critical AAIA requirements before deployment
2. Complete Annex IV technical documentation
3. Implement human oversight per Article 14
4. Conduct conformity assessment per Article 43
5. Register in EU database per Article 49
6. Establish post-market monitoring per Article 72
`
    if (input.fria?.metadata.article27Applicable) {
      report += `7. Submit FRIA to national supervisory authority per Article 27(3)
`
    }
  } else if (input.classification.riskLevel === 'limited') {
    report += `1. Implement transparency obligations per Article 50
2. Ensure AI disclosure is accessible to all users
3. Consider voluntary AAIA for best practice
`
  } else if (input.classification.riskLevel === 'prohibited') {
    report += `1. **STOP** — This system may not be deployed in the EU
2. Discontinue existing deployments immediately
3. Seek legal counsel for compliance options
`
  } else {
    report += `1. No mandatory obligations — consider voluntary codes of conduct (Article 95)
2. Consider voluntary accessibility compliance as best practice
`
  }

  report += `
---

*Generated by eu-compliance-bridge*
*EU AI Act Regulation (EU) 2024/1689*
*Report date: ${date}*
`

  return report
}
